#!/bin/bash
set -euo pipefail

say() {
	echo -e "$(/usr/bin/date -u -Ins): ${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

ARKCASE="$(type -P arkcase)" || fail "The arkcase executable could not be found in the path"

# We use a wrapper script that *should* do the right thing with
# respect to user IDs, groupIds, etc
exec "/usr/local/bin/run-developer" "${ARKCASE}" "${@}"
