#!/bin/bash

set -euo pipefail
. /.functions

#
# First, set the Java version since it may need to
# be used during the SSL initialization steps
#
/usr/local/bin/set-java

#
# Init all the SSL-related stuff
#
init_ssl

doing "Running Tomcat as: $(id)"

DEFAULT_CONFIG_WAIT=90
DEFAULT_CONFIG_URL="https://localhost:9999"

# If not specifically told otherwise, wait up to
# 90 seconds for the config server to come back up
set_or_default CONFIG_WAIT
[[ ${CONFIG_WAIT} =~ ^(0|[1-9][0-9]*)$ ]] || fail "The wait period must be a number with no leading zeros [${CONFIG_WAIT}]"

set_or_default CONFIG_URL

set_as_boolean POLL_CONFIG "true"

set_or_default BASE_DIR "/app"
set_or_default INIT_DIR "${BASE_DIR}/init"
set_or_default HOME_DIR "${BASE_DIR}/home"

# This seems to be necessary in order for the AngularResourceCopier to not puke out
cd "${HOME_DIR}" || fail "Failed to CD into the home directory [${HOME_DIR}]"
export HOME="${HOME_DIR}"

#
# This is for PostgreSQL
#
PSQL_HOME="${HOME_DIR}/.postgresql"
is_dir_readable "${PSQL_HOME}" || mkdir -p "${PSQL_HOME}" || fail "Failed to create the PG Home directory at [${PSQL_HOME}] (rc=${?})"

PSQL_ROOT_CA="${PSQL_HOME}/root.crt"
is_file_readable "${PSQL_ROOT_CA}" || ln -fsv "${CA_TRUSTS_PEM}" "${PSQL_ROOT_CA}" || fail "Failed to create the symlink from [${PSQL_ROOT_CA}] to [${CA_TRUSTS_PEM}] (rc=${?})"

if as_boolean "${POLL_CONFIG}" ; then
	# We poke at a specific path that will always return a result
	poll_url "${CONFIG_URL}/actuator/health" "${CONFIG_WAIT}" 2 || exit ${?}
else
	warn "Config server polling is disabled, continuing"
fi

#
# Set the alternate Java version, if applicable
#
set-java

ensure_dir "${WORK_DIR}"
ensure_dir "${CATALINA_TMPDIR}"

if [ ! -v NODE_ID ] ; then
	set_or_default POD_NAME "$(hostname)"
	POD_NAME="${POD_NAME%%.*}"
	[[ "${POD_NAME}" =~ ^.*-([0-9]+)$ ]] || fail "The pod name [${POD_NAME}] doesn't match the pattern for a stateful pod (must end with a number)"
	NODE_ID="${BASH_REMATCH[1]}"
else
	[[ "${NODE_ID}" =~ ^[1-9][0-9]*$ ]] || fail "The NODE_ID value [${NODE_ID}] is not a valid number"
	[ ${NODE_ID} -gt 0 ] && [ ${NODE_ID} -lt 256 ] || fail "The NODE_ID value must be in the range [1..255]"
fi

# Remove al leading zeros, just in case...
export NODE_ID="$(( 10#${NODE_ID} ))"

# This needs to exist to support the legacy deployments
set_or_default COMPONENT "arkcase"

#
# Set the environment variables for the global artifacts checksum
#
SUM_FILE="${HOME_DIR}/.artifacts.global.sums"
if is_file_readable "${SUM_FILE}" ; then
	ARTIFACTS_GLOBAL_SUMS="$(<"${SUM_FILE}")"
else
	ARTIFACTS_GLOBAL_SUMS="{ '${COMPONENT}': 'unknown' }"
	ARTIFACTS_GLOBAL_SUMS="${ARTIFACTS_GLOBAL_SUMS//\'/\"}"
fi

# We're only interested in the component's value, for now ...
export ARTIFACTS_GLOBAL_HASH="$(jq --arg COMPONENT "${COMPONENT}" -r '.[$COMPONENT]' <<< "${ARTIFACTS_GLOBAL_SUMS}")"

# Add some extra deetz to the JSON, for tracking purposes ;)
ARTIFACTS_GLOBAL_SUMS="$(jq --arg POD_NAME "${POD_NAME}" --arg TIMESTAMP "$(timestamp)" -r '. += { "pod": $POD_NAME, "timestamp": $TIMESTAMP }' <<< "${ARTIFACTS_GLOBAL_SUMS}")"
export ARTIFACTS_GLOBAL_SUMS

say "Launching the main process"

# Add the ability to modify the environment
set_or_default ENV_FILE "/.env"
[ -s "${ENV_FILE}" ] && . "${ENV_FILE}"

set_or_default LD_LIBRARY_PATH
set_or_default EXTRA_LIBRARY_DIR "${TEMP_DIR}/.libraries"
export EXTRA_LIBRARY_DIR

LD_LIBRARY_PATH+=":${EXTRA_LIBRARY_DIR}"
export LD_LIBRARY_PATH="$(sanitize_pathspec "${LD_LIBRARY_PATH}")"

[ ${#} -gt 0 ] || set -- "run"
CMD=("${TOMCAT_HOME}/bin/catalina.sh" "${@}")

# Set the session cookie name
set-session-cookie-name "${TOMCAT_HOME}/conf/context.xml"

# In development mode, we take a slight detour b/c we'll want to run
# the tomcat container in a loop so we can restart it over and over
# without crashing the pod
as_boolean "${DEVELOPMENT:-false}" && as_boolean "${DEBUG:-false}" && CMD=( run-in-loop "${CMD[@]}" )

execute "${CMD[@]}"
